"""Calculator.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1WnxD1p2MugveS2v2lonhINUc0Fy-ePIY
"""

a=int(input("Enter first number: "))
b=int(input("Enter second Number: "))
c=str(input("Enter the operator: "))
if c=="+":
  ans=a+b
  print("Sum is ",ans)
elif c=="-":
  ans=a-b
  print("Difference  is ",ans)
elif c=="*":
  ans=a*b
  print("Multiplication is ",ans)
elif c=="/":
  ans=a/b
  print("Division is ",ans)
elif c=="%":
  ans=a%b
  print("Remainder is ",ans)
elif c=="**":
  ans=a**b
  print("Exponential is ",ans)
elif c=="//":
  ans=a//b
  print("Floor Division is ",ans)
else:
  print("Incorrect operator")
