"""Company_Employee_Data.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/17xCaL2H0uqiySoOIwogD5BCCn3wZ1O6x
"""

class company:
  def __init__(self,name,age,pay):
    self.name=name
    self.age=age
    self.pay=pay
emp1=company("Ali",20,65000)
emp2=company("Khalid",40,875000)
emp3=company("Munawar",30,150000)
emp4=company("Zubair",25,200000)
print("Information of Employee one:")
print(emp1.name)
print(emp1.age)
print(emp1.pay)
print("Information of Employee two:")
print(emp2.name)
print(emp2.age)
print(emp2.pay)
print("Information of Employee three:")
print(emp3.name)
print(emp3.age)
print(emp3.pay)
print("Information of Employee four:")
print(emp4.name)
print(emp4.age)
print(emp4.pay)
